# Generated by Django 3.1.5 on 2021-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmodule', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingcart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_prod_id', models.IntegerField()),
                ('cart_cust_id', models.IntegerField()),
            ],
        ),
    ]
