# Generated by Django 3.1.5 on 2021-03-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0003_customer'),
        ('shoppingmodule', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginmodule.customer'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingmodule.product'),
        ),
    ]
