# Generated by Django 3.1.5 on 2021-03-09 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmodule', '0007_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 5, 40, 41, 167662, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=10.05),
            preserve_default=False,
        ),
    ]
