# Generated by Django 3.1.5 on 2021-03-09 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmodule', '0008_auto_20210309_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 5, 56, 59, 704102, tzinfo=utc)),
        ),
    ]
