# Generated by Django 3.1.5 on 2021-02-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_address', models.TextField()),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_img', models.ImageField(upload_to='imgs')),
                ('product_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('order_cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.cart')),
                ('order_customer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.customer')),
                ('order_product_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_customer_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.product'),
        ),
    ]
